POST http://localhost:3000/api/wilder
Content-Type : application/json

{
    "name": "Joker" 
}

###

GET http://localhost:3000/api/wilder

###

PUT http://localhost:3000/api/wilder/9
Content-Type: application/json

{
    "name": "Hulk"
}

###

DELETE http://localhost:3000/api/wilder/10

###

POST http://localhost:3000/api/wilder/1/skill/3/add
