POST http://localhost:5000/api/skill
Content-Type : application/json

{
    "name": ".Net" 
}

###

GET http://localhost:5000/api/skill

###

PUT http://localhost:5000/api/skill/8
Content-Type: application/json

{
    "name": "Javascript"
}

###

DELETE http://localhost:5000/api/skill/8

###

